services:
  db:
    image: postgres:16.3
    container_name: api_gateway_db
    environment:
      POSTGRES_DB: api_gateway
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data:
